In [4]:
from keras.models import Sequential
from keras.layers import *
import numpy as np

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

# OR function
X_or = np.array([[0,0],[0,1],[1,0],[1,1]], 'float32')
Y_or = np.array([[0],[1],[1],[1]], 'float32')

# Rest of the code...

# First architecture
model1 = Sequential()
model1.add(Dense(2, input_dim=2, activation='tanh'))
model1.add(Dense(12, activation='tanh'))
model1.add(Dense(1, activation='sigmoid'))
model1.compile(optimizer='adam', loss='binary_crossentropy')
model1.fit(X_or, Y_or, batch_size=1, epochs=200, verbose=0)
print("OR Function Predictions:")
print(model1.predict(X_or))

# Second architecture
model2 = Sequential()
model2.add(Dense(4, input_dim=2, activation='tanh'))
model2.add(Dense(8, activation='tanh'))
model2.add(Dense(1, activation='sigmoid'))
model2.compile(optimizer='adam', loss='binary_crossentropy')
model2.fit(X_or, Y_or, batch_size=1, epochs=200, verbose=0)
print("\nOR Function Predictions (Second Architecture):")
print(model2.predict(X_or))
print(model2.predict(X_or))



1/1 [==============================] - 0s 69ms/step
[[0.50501245]
 [0.53572977]
 [0.46996292]
 [0.48120672]]
OR Function Predictions:
1/1 [==============================] - 0s 55ms/step
[[0.39655912]
 [0.90903974]
 [0.87679154]
 [0.9743619 ]]



OR Function Predictions (Second Architecture):
1/1 [==============================] - 0s 59ms/step
[[0.37605637]
 [0.81675386]
 [0.9548992 ]
 [0.973852  ]]
1/1 [==============================] - 0s 21ms/step
[[0.37605637]
 [0.81675386]
 [0.9548992 ]
 [0.973852  ]]
